#!/usr/bin/bash

unclutter -root -idle 0.1 &

DOMAIN=$(grep 'xmpp-domain' /etc/jitsi/jibri/jibri.conf | cut -d'"' -f2)
if [[ -n "$DOMAIN" ]]; then
    FQDN="https://$DOMAIN"
else
    FQDN="about:blank"
fi

if [[ "$DISPLAY" = ":0" ]]; then
    rm -rf ~/.config/chromium
    timeout 8 /usr/bin/chromium --ignore-certificate-errors $FQDN &
fi

#[[ "$DISPLAY" = ":0" ]] && \
#    x11vnc -display :0 -rfbport 5900 -nolookup -once -loop -usepw -shared \
#    -noxdamage -nodpms &

#[[ "$DISPLAY" = ":1" ]] && \
#    x11vnc -display :1 -rfbport 5901 -nolookup -once -loop -usepw -shared \
#    -noxdamage -nodpms &
